pipeline {
    agent { label 'docker-agent-label' }

    environment {
        AWS_ACCOUNT_ID = '571600845308'
        AWS_REGION = 'ap-south-1'
        EC2_USER = 'ubuntu'
        EC2_HOST = '3.110.51.85'
        APP_DIR = '/home/ubuntu/todo-app'
        PYTHON_BIN = '/usr/bin/python3'
    }

    stages {
        stage('Clone Repository') {
            steps {
                withCredentials([string(credentialsId: 'aasmin', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    echo "Cloning repository..."
                    git clone https://$GITHUB_TOKEN@github.com/
                    '''
                }
            }
        }

        stage('Run Pylint Checks') {
            steps {
                sh '''
                echo "Running Pylint Checks..."
                chmod +x pylint.sh
                ./pylint.sh
                '''
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['858d053b-55ec-4c46-9cb6-22f757cae15c']) {
                    sh '''
                    echo "Transferring application files to EC2..."
                    ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "mkdir -p $APP_DIR"
                    scp -o StrictHostKeyChecking=no -r ./* $EC2_USER@$EC2_HOST:$APP_DIR

                    echo "Starting application using Uvicorn..."
                    ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
                    cd $APP_DIR
                    source venv/bin/activate

                    echo "Restarting Uvicorn if already running..."
                    pkill -f "uvicorn" || true
                    
                    echo "Starting Uvicorn..."
                    nohup uvicorn app:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
                    EOF
                    '''
                }
            }
        }
    }
}
